### ISSUE TITLE
Generated Kettle file error on foreign key constraint

### ISSUE THREAD

**Issue by jpmeijers** [dalibo/sqlserver2pgsql#140]
```
2021/01/19 08:02:48 - Migration - Starting entry [Common_Aggregate]
2021/01/19 08:02:48 - Common_Aggregate - Running transformation using the Kettle execution engine
2021/01/19 08:02:48 - [Common].[Aggregate] - Dispatching started for transformation [[Common].[Aggregate]]
2021/01/19 08:02:48 - Table output.3 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Table output.0 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Table output.2 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Table output.5 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Table output.4 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Table output.1 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Table output.6 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Table output.7 - Connected to database [__postgres_db__] (commit=100)
2021/01/19 08:02:48 - Execute SQL script.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : An error occurred, processing will be stopped: 
2021/01/19 08:02:48 - Execute SQL script.0 - Couldn't execute SQL: truncate table "common"."aggregate"
2021/01/19 08:02:48 - Execute SQL script.0 - 
2021/01/19 08:02:48 - Execute SQL script.0 - ERROR: cannot truncate a table referenced in a foreign key constraint
2021/01/19 08:02:48 - Execute SQL script.0 -   Detail: Table "deviceport" references "aggregate".
2021/01/19 08:02:48 - Execute SQL script.0 -   Hint: Truncate table "deviceport" at the same time, or use TRUNCATE ... CASCADE.
2021/01/19 08:02:48 - Execute SQL script.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Error initializing step [Execute SQL script]
2021/01/19 08:02:48 - [Common].[Aggregate] - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Step [Execute SQL script.0] failed to initialize!
2021/01/19 08:02:48 - Table input.0 - Finished reading query, closing connection.
2021/01/19 08:02:48 - Execute SQL script.0 - Finished reading query, closing connection.
2021/01/19 08:02:48 - Common_Aggregate - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unable to prepare for execution of the transformation
2021/01/19 08:02:48 - Common_Aggregate - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2021/01/19 08:02:48 - Common_Aggregate - We failed to initialize at least one step.  Execution can not begin!
2021/01/19 08:02:48 - Common_Aggregate - 
2021/01/19 08:02:48 - Common_Aggregate - 
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:1282)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.trans.Trans.execute(Trans.java:751)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.entries.trans.JobEntryTrans.execute(JobEntryTrans.java:1188)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.execute(Job.java:682)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.execute(Job.java:823)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.execute(Job.java:823)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.execute(Job.java:823)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.execute(Job.java:823)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.execute(Job.java:823)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.execute(Job.java:500)
2021/01/19 08:02:48 - Common_Aggregate - 	at org.pentaho.di.job.Job.run(Job.java:386)
2021/01/19 08:02:48 - Migration - Finished job entry [Common_Aggregate] (result=[false])
2021/01/19 08:02:48 - Migration - Finished job entry [BillComparison_CommunityDevicePortType] (result=[false])
2021/01/19 08:02:48 - Migration - Finished job entry [BillComparison_BillComparisonDetail] (result=[false])
2021/01/19 08:02:48 - Migration - Finished job entry [BillComparison_BillComparison] (result=[false])
2021/01/19 08:02:48 - Migration - Finished job entry [SQL SCRIPT START] (result=[false])
2021/01/19 08:02:48 - Migration - Job execution finished
2021/01/19 08:02:48 - Finished!
2021/01/19 08:02:48 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Finished with errors
08:02:48,416 ERROR [di] null Finished with errors
2021/01/19 08:02:48 - Start=2021/01/19 08:02:44.628, Stop=2021/01/19 08:02:48.416
2021/01/19 08:02:48 - Processing ended after 3 seconds.
```

Please let me know if you need any more details.

**Comment by jpmeijers** [comment]
The suggestion to add `cascade` to the end of the query seems to work. That is the `truncate` query in the `kjb` file for the respective table.

**Comment by jpmeijers** [comment]
Another workaround that saves one from editing all the kjb files, is to run `tables-before.sql`, then do the kettle migration, and only then apply the constraints in `tables-after.sql` and `tables-unsure.sql`. Maybe this is documented and I missed it.

**Comment by madtibo** [comment]
Hello @jpmeijers 

This is not documented. Both could be done.

* add a CASCADE in the kjb file: should we add the order unconditionally in the [kjb file](https://github.com/dalibo/sqlserver2pgsql/blob/master/sqlserver2pgsql.pl#L3361) or should there be an option for that?
* This is a good idea to add a section in the [FAQ](https://github.com/dalibo/sqlserver2pgsql/blob/master/FAQ.md)

**Comment by jpmeijers** [comment]
The error only occurs if one tries to truncate the tables after the constraints have been added to the tables. I think the safest solution is just to document that the `migration.kjb` file should be run between running `tables-before.sql` and `tables-after.sql`. 

There is a possibility that the order in which the migration.kjb migrates the tables could result in previously imported tables during the same job being cascade deleted.

**Comment by madtibo** [comment]
OK, not a good idea to truncate then.

For the FAQ, what do you think of:

In which order should I run the operations?
----------------------------------
sqlserver2pgsql outputs several files: before, after, unsure SQL files, plus the kettle jobs files.
If you load all the SQL files before the data migration, you can experience problems. For example, you can have errors when the kettle job truncates the table at the start of the process. If a foreign key constraint is enforced, PostgreSQL cannot truncate a table referenced in a foreign key constraint and the job would error out.
You should first check the unsure file, verify that the SQL is fine or correct it it needed. Some SQL orders from the unsure files are to be run before the data migration, for example, default column values, procedures or functions, triggers. So move them to the before file.
You can then load the before file. Then use the kettle jobs to migrate the data. When this is done, load the rest of the unsure and the after file.

**Comment by jpmeijers** [comment]
Yes, that is very clear. Small typo in `or correct it it needed` => `if needed`.

Regarding the kettle jobs, maybe it is worthwhile being explicit when one should run the `incremental.kjb` files too.

As far as I understand the order will be (if we have no unsures):
* tables-before.sql
* migration.kjb
* tables-after.sql
* incremental.kjb (periodically)

**Comment by madtibo** [comment]
PR with FAQ update is merged.

Thank you for the review!
