### ISSUE TITLE
Is the PDI is still alive?

### ISSUE THREAD

**Issue by Medzon888** [dalibo/sqlserver2pgsql#183]
Hello, maybe a question is not about sqlserver2pg but on pentaho git page issues is not available.

So question is, PDI is working? I was trying many ways for install it but no luck. 

A) Variant with a manual downloading(spoon.sh)

1) Download 
`
wget https://privatefilesbucket-community-edition.s3.us-west-2.amazonaws.com/9.4.0.0-343/ce/client-tools/pdi-ce-9.4.0.0-343.zip
`
2) Launch spoon.sh and got error:
```
#######################################################################
WARNING:  no libwebkitgtk-1.0 detected, some features will be unavailable
    Consider installing the package with apt-get or yum.
    e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
(java:42326): Gdk-WARNING **: 08:10:12.496: The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4621)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1038)
        at org.eclipse.swt.widgets.Display.create(Display.java:1025)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:179)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:590)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:581)
        at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:679)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
        
```
        
hardcode of warning about libwebkitgtk-1.0-0 - i was install last version from repository 
`apt install libwebkitgtk-6.0-4	`
Warning about GDK_NATIVE_WINDOWS can be skipped with comment this variable in spoon.sh

Any suggestions about how to handle with it? Need a fresh cases who handled with it.

B) Variant with a git install  https://github.com/pentaho/pentaho-kettle

I was install Java, Maven and trying to build but have a trouble with unavailable addres for artifact in pom.xml
```
[ERROR]   The project org.pentaho.di:pdi:10.2.0.0-SNAPSHOT (/root/pentaho-kettle/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.pentaho.di:pdi:10.2.0.0-SNAPSHOT: The following artifacts could not be resolved: org.pentaho:pentaho-ce-jar-parent-pom:pom:10.2.0.0-SNAPSHOT (absent): Could not find artifact org.pentaho:pentaho-ce-jar-parent-pom:pom:10.2.0.0-SNAPSHOT in pentaho-public (https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/) and 'parent.relativePath' points at wrong local POM @ line 16, column 11 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: The following artifacts could not be resolved: org.pentaho:pentaho-ce-jar-parent-pom:pom:10.2.0.0-SNAPSHOT (absent): Could not find artifact org.pentaho:pentaho-ce-jar-parent-pom:pom:10.2.0.0-SNAPSHOT in pentaho-public (https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/)
```

Its my first attempt with data integrators. If somebody know a clear answer of how to install kettle please help :)

**Comment by linweipeng200312** [comment]
thanks for the PDI download link, I can run it successfully.
- install  java JDK 8
- set the correct java environment
- change the Spoon.bat I upload my bat for your information
    if "%KETTLE_DIR%"=="" set KETTLE_DIR=%~dp0 
    if "%KETTLE_DIR:~-1%"=="\" set KETTLE_DIR=%KETTLE_DIR:~0,-1%

[Spoon.zip](https://github.com/user-attachments/files/19243972/Spoon.zip)

**Comment by marco44** [comment]
Another possibility would probable to use a more recent PDI, https://hitachiedge1.jfrog.io/ui/native/pntpub-maven-release-cache/org/pentaho/di/pdi-ce/. That may make it possible to use more recent versions of the JDK, which would probably use a later version of libs.
But not sure if this helps, I've not used PDI for years now

**Comment by cobolbaby** [comment]
https://github.com/ambientelivre/legacy-pentaho-ce
